### ISSUE TITLE
Podspec is overwriting SWIFT_VERSION

### ISSUE THREAD

**Issue by shaibt** [beryu/CustomizableActionSheet#12]
Hi,

The CustomizableActionSheet.podspec includes the following:
`
s.xcconfig = {
    'SWIFT_VERSION' => '3.0'
  }
`

This overwrites target projects SWIFT version (which for newer projects are 3.1) and causes this CocoaPods error:

>  [!] The `My-Project [Debug]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-My-Project/Pods-My-Project.debug.xcconfig'. This can lead to problems with the CocoaPods installation

I think best practice is not to include the SWIFT_VERSION in your pod spec - see reference [here](https://github.com/CocoaPods/CocoaPods/issues/5952)

**Comment by beryu** [comment]
@shaibt 
Thanks for reporting!
I fixed it with #13, and released it.
Please try again and could you tell me the result?

**Comment by shaibt** [comment]
@beryu Seems it has. Thanks!

**Comment by beryu** [comment]
Thanks for replying.
I glad to resolve it!
