### ISSUE TITLE
Enabling scroll?

### ISSUE THREAD

**Issue by Diogo72** [beryu/CustomizableActionSheet#14]
Is it possible to enable scroll? When I add too many actions some of them go offscreen.

**Comment by beryu** [comment]
Action Sheet can't scroll itself.
But, you can add a scrollable item as CustomizableActionSheetItem.
Please consider this approach.

```swift
let actionSheet = CustomizableActionSheet()
var items = [CustomizableActionSheetItem]()

// Add tableView as CustomizableActionSheetItem including too many actions.
let tableView = YourTableView()
tableView.items = someDataSource.items()

let tableViewItem = CustomizableActionSheetItem(type: .view, height: tableView.height())
tableViewItem.view = tableView
items.append(tableViewItem)

actionSheet.showInView(self.view, items: items)
```

**Comment by Diogo72** [comment]
I tried doing that, but it's not working. Most times I can't even see my cells and when I can, when I try to scroll they all disappear. Any clues?

**Comment by beryu** [comment]
@Diogo72 
[Here is example with too many items.](https://github.com/beryu/CustomizableActionSheet/files/1119449/ActionSheetSample.zip)
Please try it.

**Comment by Diogo72** [comment]
Thank you so much for your quick answers, I now realize what was my problem. The view I was passing to CustomizableActionSheetItem was from a TableViewController instantiated in the same method. So, when the method ended, the reference was lost and the view deallocated, leading to the tableview becoming empty. In short: my problem, nothing wrong with the lib.

Thanks again and sorry for wasting your time.
