### ISSUE TITLE
Bug: Action sheet cuts off if used in a ScrollView

### ISSUE THREAD

**Issue by annjawn** [beryu/CustomizableActionSheet#15]
The action sheet would cut off from the bottom if it is used in a scrollview and if the scrollable content goes beyond the UIScreen. 

This is due to this line in the code in the `showInView` method-

 ```
 public func showInView(_ targetView: UIView, items: [CustomizableActionSheetItem], closeBlock: (() -> Void)? = nil) {
    // Save instance to reaction until closing this sheet
    CustomizableActionSheet.actionSheets.append(self)

let screenBounds = UIScreen.main.bounds
.....
```
  
The `screenBounds` should take `targetView.bounds` instead of `UIScreen.main.bounds` which resolves the issue.

```
  public func showInView(_ targetView: UIView, items: [CustomizableActionSheetItem], closeBlock: (() -> Void)? = nil) {
    // Save instance to reaction until closing this sheet
    CustomizableActionSheet.actionSheets.append(self)

    let screenBounds = targetView.bounds
```

**Comment by beryu** [comment]
@annjawn Thank you for reporting!
I fixed it in #16, and [released it as 1.0.8](https://github.com/beryu/CustomizableActionSheet/releases/tag/1.0.8).
