### ISSUE TITLE
Actionsheet under tabbar

### ISSUE THREAD

**Issue by MarvinNazari** [beryu/CustomizableActionSheet#6]
Hi, awesome project, but the action sheet goes under tabbar.

**Comment by beryu** [comment]
Thank you for reporting.

`CustomizableActionSheet#showInView` can be specified a view for putting Action sheet.
If you are developing "Tabbed Application", Please get view with `self.tabBarController?.view` on your ViewController, and specify it to `CustomizableActionSheet#showInView`.

For example:

``` swift
if let view = self.tabBarController?.view {
  let actionSheet = CustomizableActionSheet()
  actionSheet.showInView(view , items: items)
}
```

**Comment by beryu** [comment]
I will close this issue.
