### ISSUE TITLE
Invisible

### ISSUE THREAD

**Issue by LiveRock** [beryu/CustomizableActionSheet#7]
I studied the example and also use the code for tabbar controller but when the actionsheet, it is invisible.

when I comment out the items.append(sampleView), I can see a CANCEL button.

It seem that something is wrong with my sampleview xib but i can figure it out.

HELP!

**Comment by beryu** [comment]
I made example project by tabbed application.
[Here is Xcode project file (CocoaPods required).](https://github.com/beryu/CustomizableActionSheet/files/346112/TabbedAppSample.zip)

If you can't debug after watching this project file, Please show me your project file?

**Comment by LiveRock** [comment]
Hi Ryuta

I still cannot make it work

When I commented out the below:

profilePicViewItem.type = .View

I get a white action sheet with a cancel button and the cancel button works.

But my view does not appear.

Your code works. It is something to do with my project but I can’t seem to find out what is wrong.

Is there something special about the UIview?

Thanks and hope to hear from you soon.

Peter

**Comment by LiveRock** [comment]
Dear Ryuta

Here is my code section:

// Action sheet

        var items = [CustomizableActionSheetItem]()

        // Setup custom view

        if let myProfilePicView = UINib(nibName: "ProfilePicView", bundle: nil).instantiateWithOwner(self, options: nil)[0] as? ProfilePicView {

        

        let bundle = NSBundle.mainBundle()

        let nib = UINib(nibName: "ProfilePicView", bundle: bundle)

        //if let myProfilePicView = nib.instantiateWithOwner(self, options: nil)[0] as? ProfilePicView {

       //var myProfilePicView = ProfilePicViewClass.instanceFromNib()

            print("Inside nib")

            myProfilePicView.delegate = self

            let profilePicViewItem = CustomizableActionSheetItem()

            

            profilePicViewItem.view = myProfilePicView

            profilePicViewItem.type = .View

            profilePicViewItem.height = 200

            items.append(profilePicViewItem)

        }

        

        // Setup button

        let closeItem = CustomizableActionSheetItem()

        closeItem.type = .Button

        closeItem.label = "Cancel"

        closeItem.selectAction = { (actionSheet: CustomizableActionSheet) -> Void in

            actionSheet.dismiss()

        }

        items.append(closeItem)

        

        // Show

        

        if let view = self.tabBarController?.view {

            let actionSheet = CustomizableActionSheet()

            actionSheet.showInView(view , items: items)

        }

**Comment by beryu** [comment]
Did you fill this field (below's screenshot) on your `ProfilePicView.xib` ?
I tried to be empty this field on my xcode project, and I get action sheet with cancel button only(maybe same result with yours).
![screenshot](https://cloud.githubusercontent.com/assets/202968/16574396/55eb7934-42b9-11e6-9eb2-0962df7da8f7.png)

**Comment by LiveRock** [comment]
Hi

Yes, I did. Thans for getting back to me.

I will try other wasy and get back to you.

Regards,

Peter

**Comment by LiveRock** [comment]
Hi Ryuta

I tried to delete my xib and rlated swift file and recreate a new one from scratch.

Same results. I wonder what is going on on my side

Peter

**Comment by sulamatraore** [comment]
I am also getting this issue. It happens only on modal view controllers. Any idea how to fix this? Thanks in advance!

**Comment by beryu** [comment]
Hi Sulama

It maybe solve with specifying modal view controller's view to `CustomizableActionSheet#showInView()` .

If you can't solve this issue, Could you show me your Xcode project?
(I hope you to upload simple Xcode project with zip format)

**Comment by beryu** [comment]
Many time passed from the last comment.
So, I just close this.
