### ISSUE TITLE
Swift3 and Xcode8?

### ISSUE THREAD

**Issue by chriscohoat** [beryu/CustomizableActionSheet#9]
Thanks for the awesome library! I'm having build errors with Swift3 and Xcode8 while using either the `swift3` branch or `master` branch.

I'm using:

```
pod 'CustomizableActionSheet', :git => 'https://github.com/beryu/CustomizableActionSheet', :branch => 'swift3'
```

And have a number of build errors. I noticed #8 is open but neither branches seem to work for my project.

Any suggestions?

**Comment by beryu** [comment]
Thank you for reporting!
I can't check detail at now, but I will try within 24 hours.
(Because of my hard work, sorry.)

**Comment by beryu** [comment]
@chriscohoat 
Sorry for my mistake.

I forgot to save new file under "[Source](https://github.com/beryu/CustomizableActionSheet/tree/master/Source)" directory.
Error was occurred by building with Swift2.2 style file by CocoaPods.

I committed Swift3 style file to correct directory, and now we can build with Swift3 in case of installed via CocoaPods!
I applied this change to master. So just write Podfile like below:

``` ruby
pod 'CustomizableActionSheet'
```

Please check it.

**Comment by chriscohoat** [comment]
Thanks for your hard work @beryu! It works great. 1.0.6 indeed works perfectly with Xcode 8 and Swift 3. Appreciate it.

**Comment by beryu** [comment]
Thank you for your review!
I will close this issue.
